import { z } from 'zod';
import { LEXICAL_EVIDENCE_VERSION } from './types';

const category = z.enum(['PERSON_NAME', 'PLACE_NAME', 'WORK_TITLE', 'ORGANIZATION_NAME', 'MULTIWORD_EXPRESSION', 'LEXICAL_TERM', 'UNCLASSIFIED_CANDIDATE']);
const citation = z.object({ sourceRecordId: z.string().min(1), sourceUrl: z.string().url(), sourceField: z.enum(['title', 'dc:creator']), observedForm: z.string().min(1), evidenceStatus: z.literal('OBSERVED') }).strict();
export const lexicalCandidateSchema = z.object({
  schemaVersion: z.literal(LEXICAL_EVIDENCE_VERSION), candidateId: z.string().regex(/^lex-[a-f0-9]{20}$/u), originalPersianForm: z.string().min(1), normalizedSearchForm: z.string().min(1), category, contextualIdentity: z.string().min(1), linguisticContext: z.object({ kind: z.enum(['BIBLIOGRAPHIC_TITLE', 'CREATOR_FIELD']), fullText: z.string().min(1), uncertainEntityType: z.boolean() }).strict(), sourceRecordIds: z.array(z.string().min(1)).min(1), sourceUrls: z.array(z.string().url()).min(1), fieldProvenance: z.array(citation).min(1), observedLatinVariants: z.array(z.object({ value: z.string().min(1), classification: z.enum(['ROMANIZATION_CANDIDATE', 'TRANSLATED_TITLE', 'UNDETERMINED_LATIN_VARIANT']), sourceField: z.string().min(1), sourceRecordId: z.string().min(1) }).strict()), bibliographicIdentities: z.array(z.object({ recordId: z.string().min(1), identityStatus: z.enum(['UNIQUE_RECORD', 'EXACT_DUPLICATE_RECORD', 'DUPLICATE_MANIFESTATION', 'RELATED_EDITION', 'SIMILAR_TITLE_ONLY', 'UNCERTAIN_RELATIONSHIP']), crid: z.string().nullable(), ncid: z.string().nullable(), isbns: z.array(z.string()), oclcs: z.array(z.string()) }).strict()).min(1), evidenceCount: z.number().int().positive(), distinctSourceCount: z.number().int().positive(), reviewStatus: z.enum(['UNREVIEWED', 'REVIEWED']), authorityStatus: z.enum(['NON_AUTHORITATIVE_CANDIDATE', 'HUMAN_REVIEWED']), evidenceStatus: z.enum(['OBSERVED', 'CANDIDATE', 'REVIEWED', 'CONFLICTING']), extractionMethod: z.literal('WHOLE_BIBLIOGRAPHIC_FIELD'), extractionVersion: z.literal('phase8e-v1'), contentHash: z.string().regex(/^[a-f0-9]{64}$/u)
}).strict().superRefine((value, context) => { if ((value.reviewStatus === 'REVIEWED') !== (value.authorityStatus === 'HUMAN_REVIEWED')) context.addIssue({ code: z.ZodIssueCode.custom, message: 'Review and authority states must agree.' }); });
export const lexicalEvidenceArtifactSchema = z.object({ schemaVersion: z.literal('phase8e-lexical-artifact-v1'), datasetVersion: z.literal(LEXICAL_EVIDENCE_VERSION), generatedAt: z.string().datetime(), sourceMode: z.enum(['OFFLINE_PHASE8D_FIXTURE', 'LIVE_CINII']), liveStatus: z.enum(['LIVE_NOT_RUN_MISSING_AUTHORIZATION', 'LIVE_RUN_AUTHORIZED']), candidates: z.array(lexicalCandidateSchema) }).strict();
