import { z } from 'zod';
import { CINII_DATASET_VERSION } from './types';

export const ciniiQuerySchema = z.object({ queryId: z.string().min(1), q: z.string().min(1).optional(), title: z.string().min(1).optional(), languageType: z.array(z.string().regex(/^[a-z]{2}$/u)).optional(), dataSourceType: z.array(z.enum(['CIB', 'NACSIS_CAT'])).optional(), resourceType: z.array(z.string().min(1)).optional(), from: z.string().regex(/^\d{4}(?:\d{2})?$/u).optional(), until: z.string().regex(/^\d{4}(?:\d{2})?$/u).optional(), sortorder: z.union([z.literal(0), z.literal(1), z.literal(4)]), count: z.number().int().min(1).max(100) }).strict().refine((value) => Boolean(value.q || value.title), 'A declared q or title query is required.');

const rawItem = z.object({ '@id': z.string().url(), '@type': z.union([z.string(), z.array(z.string())]).optional(), title: z.unknown(), link: z.unknown().optional(), 'rdfs:seeAlso': z.unknown().optional(), 'dc:creator': z.unknown().optional(), 'dc:publisher': z.unknown().optional(), 'dc:language': z.unknown().optional(), 'prism:publicationDate': z.unknown().optional(), 'dcterms:hasPart': z.unknown().optional(), ncid: z.unknown().optional(), isbn: z.unknown().optional() }).passthrough();
export const ciniiResponseSchema = z.object({ 'opensearch:totalResults': z.union([z.number(), z.string()]), 'opensearch:startIndex': z.union([z.number(), z.string()]), 'opensearch:itemsPerPage': z.union([z.number(), z.string()]), items: z.array(rawItem).default([]) }).passthrough();

const titleVariant = z.object({ value: z.string().min(1), language: z.string().optional(), sourceField: z.string().min(1) }).strict();
export const ciniiEvidenceRecordSchema = z.object({
  schemaVersion: z.literal('phase8d-cinii-evidence-v1'), datasetVersion: z.literal(CINII_DATASET_VERSION), recordId: z.string().min(1), sourceProvider: z.literal('CINII_RESEARCH_OPENSEARCH_V2'), sourceRecordId: z.string().min(1), sourceUrl: z.string().url(), retrievedAt: z.string().datetime(), queryId: z.string().min(1), recordType: z.string().nullable(), rawTitles: z.array(titleVariant).min(1), persianTitle: z.string().nullable(), normalizedPersianTitle: z.string().nullable(), observedRomanizations: z.array(z.object({ value: z.string().min(1), probableScheme: z.literal('UNKNOWN'), sourceField: z.string().min(1) }).strict()), languageEvidence: z.object({ catalogLanguages: z.array(z.string()), unicodeEvidence: z.array(z.string()), linguisticIdentity: z.enum(['PERSIAN_SUPPORTED', 'UNCERTAIN']) }).strict(), scriptClassification: z.enum(['PERSIAN_SCRIPT', 'ARABIC_SCRIPT_UNCERTAIN_LANGUAGE', 'MIXED_ARABIC_LATIN', 'LATIN_ONLY', 'OTHER_SCRIPT']), authors: z.array(z.string()), publicationMetadata: z.object({ publisher: z.string().nullable(), publicationYear: z.number().int().nullable() }).strict(), identifiers: z.object({ crid: z.string().nullable(), ncid: z.string().nullable(), isbns: z.array(z.string()) }).strict(), pairingStatus: z.enum(['PERSIAN_ONLY', 'PERSIAN_WITH_OBSERVED_ROMANIZATION', 'MULTIPLE_ROMANIZATION_VARIANTS', 'LATIN_ONLY', 'UNCERTAIN_LANGUAGE_OR_PAIRING']), pairingEvidence: z.array(z.string()), bibliographicIdentityStatus: z.enum(['UNIQUE_RECORD', 'EXACT_DUPLICATE_RECORD', 'DUPLICATE_MANIFESTATION', 'RELATED_EDITION', 'SIMILAR_TITLE_ONLY', 'UNCERTAIN_RELATIONSHIP']), relatedRecordIds: z.array(z.string()), reviewStatus: z.literal('UNREVIEWED'), provenance: z.object({ endpoint: z.literal('https://cir.nii.ac.jp/opensearch/v2/books'), officialDocumentation: z.string().url(), attribution: z.string().min(1), licenseNote: z.string().min(1), originalSourceFields: z.array(z.string()) }).strict(), rawRecordChecksum: z.string().regex(/^[a-f0-9]{64}$/u), contentHash: z.string().regex(/^[a-f0-9]{64}$/u)
}).strict();
