import type { PhraseContextKind, PhraseResolution } from '../../../domain/assistance';
import type { PresentationContentCategory, PresentationDiagnosticSeverity } from '../../../domain/presentation/types';

export const PHASE8C_DATASET_VERSION = 'phase8c-accuracy-pilot-v1' as const;
export const PHASE8C_TAXONOMY_VERSION = 'phase8c-error-taxonomy-v1' as const;

export type ReferenceStatus = 'UNREVIEWED' | 'REVIEW_PENDING' | 'INDEPENDENTLY_REVIEWED' | 'ADJUDICATION_REQUIRED' | 'ADJUDICATED';
export type EvaluationSplit = 'DEVELOPMENT_DIAGNOSTIC' | 'LOCKED_EVALUATION';
export type SamplingStratum = 'BOOK_OR_ARTICLE_TITLE' | 'PERSONAL_OR_GEOGRAPHICAL_NAME' | 'TECHNICAL_OR_HISTORICAL_TERM' | 'IZAFAT_OR_MORPHOLOGY' | 'AMBIGUOUS_OR_DIFFICULT';
export type ErrorCategory = 'LEXICAL_READING_ERROR' | 'SHORT_VOWEL_ERROR' | 'LONG_VOWEL_ERROR' | 'CONSONANT_MAPPING_ERROR' | 'IZAFAT_DETECTION_ERROR' | 'IZAFAT_RENDERING_ERROR' | 'MORPHOLOGY_ERROR' | 'COMPOUND_BOUNDARY_ERROR' | 'PROPER_NAME_ERROR' | 'HAMZA_AYN_ERROR' | 'IJMES_PRESENTATION_ERROR' | 'TOKEN_ALIGNMENT_ERROR' | 'MODEL_UNCERTAINTY' | 'VALIDATOR_FALSE_NEGATIVE' | 'VALIDATOR_FALSE_POSITIVE' | 'REFERENCE_DISPUTE' | 'OTHER';
export type FeatureKind = 'SHORT_VOWEL' | 'LONG_VOWEL' | 'CONSONANT' | 'IZAFAT_PRESENCE' | 'IZAFAT_REALIZATION' | 'MORPHOLOGICAL_SUFFIX' | 'COMPOUND_BOUNDARY' | 'PROPER_NAME' | 'HAMZA' | 'AYN';

export interface SourceProvenance { sourceType: 'USER_OBSERVED_DIAGNOSTIC' | 'BIBLIOGRAPHIC_RECORD' | 'SCHOLAR_SUPPLIED' | 'SYNTHETIC_TEST_FIXTURE'; sourceId: string; citation: string; url?: string; accessedAt?: string; licenseNote: string; }
export interface ScholarReview { status: ReferenceStatus; reviewerId?: string; reviewerRole?: string; reviewedAt?: string; adjudicatorId?: string; adjudicatedAt?: string; notes?: string; }
export interface ReferenceToken { tokenIndex: number; surface: string; canonical: string; morphology?: string[]; }
export interface ReferenceFeature { id: string; kind: FeatureKind; scope: 'PHRASE' | 'TOKEN' | 'RELATION'; tokenIndexes: number[]; expected: string; }
export interface ReferenceAnnotation { primaryCanonical: string; acceptedAlternatives: string[]; tokens: ReferenceToken[]; features: ReferenceFeature[]; izafatRelations: Array<{ sourceTokenIndex: number; targetTokenIndex: number; realization: '-i' | '-yi'; }>; properNameConventions: string[]; ijmesConsiderations: string[]; citations: string[]; adjudicationNotes?: string; }
export interface DiagnosticObservation { observedDraft: string; questions: string[]; suspectedErrors: ErrorCategory[]; disclaimer: string; }
export interface AccuracyCase { id: string; datasetVersion: typeof PHASE8C_DATASET_VERSION; originalPersian: string; normalizedInput: string; contextKind: PhraseContextKind; contentCategory: PresentationContentCategory; stratum: SamplingStratum; split: EvaluationSplit; duplicateGroupId: string; provenance: SourceProvenance; review: ScholarReview; reference: ReferenceAnnotation | null; diagnosticObservation?: DiagnosticObservation; }
export interface AccuracyCorpus { schemaVersion: 'phase8c-corpus-schema-v1'; datasetVersion: typeof PHASE8C_DATASET_VERSION; cases: AccuracyCase[]; }
export interface AccuracyManifest { schemaVersion: 'phase8c-manifest-schema-v1'; datasetVersion: typeof PHASE8C_DATASET_VERSION; selectionAlgorithm: 'independent-curation-v1'; splitAlgorithm: 'sha256-grouped-phase8c-v1'; canonicalization: 'stable-key-order-json-v1'; corpusSha256: string; caseCount: number; reviewedCaseCount: number; splitCounts: Record<EvaluationSplit, number>; sourceIds: string[]; }

export interface ValidatorGroundTruth { structuralError: boolean | null; deterministicConsistencyError: boolean | null; policySeverity: PresentationDiagnosticSeverity | 'NONE' | null; linguisticReviewRequired: boolean | null; }
export interface AccuracyPrediction { caseId: string; provider: string; model: string; promptVersion: string; responseClassification: 'PROPOSED' | 'REVIEW_REQUIRED' | 'PROVIDER_FAILURE' | 'TIMEOUT'; validationPassed: boolean; validationErrors: string[]; canonicalProposal: string | null; renderedFull: string | null; renderedIjmesPublication: string | null; tokenReadings: Array<{ tokenIndex: number; surface: string; canonical: string; }>; predictedFeatures: Array<{ referenceFeatureId: string; value: string; }>; warnings: string[]; assumptions: string[]; errorCategories: ErrorCategory[]; validatorSignals: Array<{ layer: 'STRUCTURAL' | 'DETERMINISTIC_CONSISTENCY' | 'IJMES_POLICY' | 'LINGUISTIC_REVIEW'; severity: PresentationDiagnosticSeverity; }>; validatorGroundTruth?: ValidatorGroundTruth; durationMs: number; resolution?: PhraseResolution; }
export interface EvaluationInput { runKind: 'OFFLINE_MOCKED' | 'LIVE_OPENAI'; corpus: AccuracyCorpus; predictions: AccuracyPrediction[]; }

export interface ProportionMetric { numerator: number; denominator: number; percent: number | null; wilson95: { low: number; high: number } | null; }
export interface ValidatorMatrix { trueDetectedErrors: number; missedErrors: number; falseWarnings: number; correctUnflagged: number; uncertain: number; signalCounts: Record<PresentationDiagnosticSeverity, number>; precision: ProportionMetric; recall: ProportionMetric; }
export interface EvaluationReport { schemaVersion: 'phase8c-evaluation-report-v1'; runKind: EvaluationInput['runKind']; datasetVersion: string; totalCases: number; reviewedCases: number; evaluatedCases: number; excludedCases: number; failureCases: number; phrase: { exact: ProportionMetric; acceptedAlternative: ProportionMetric; normalizedReference: ProportionMetric; caseOnlyDifference: number; unicodeOnlyDifference: number; }; tokens: { correct: number; incorrect: number; unalignable: number; alignmentAmbiguity: number; evaluatedDenominator: number; accuracy: ProportionMetric; }; features: Record<FeatureKind, { correct: number; incorrect: number; unevaluable: number }>; presentation: { fullScholarly: ProportionMetric; ijmesPublication: ProportionMetric; }; validator: Record<'STRUCTURAL' | 'DETERMINISTIC_CONSISTENCY' | 'IJMES_POLICY' | 'LINGUISTIC_REVIEW', ValidatorMatrix>; correctionProxy: { phrasesNeedingCorrection: number; tokensNeedingCorrection: number; completeReanalysisCases: number; note: string; }; errors: Record<ErrorCategory, number>; exclusions: Array<{ caseId: string; reason: string }>; }
