import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it, vi } from 'vitest';
import { assertSafeEvidenceWrite, environmentFromProcess, type WriteEnvironment } from './guard';
import { importBsbEvidence, restoreSnapshot } from './ingestion';
import { MemoryEvidenceRepository, MemoryRawArchive } from './memory';
import { searchActiveEvidence, searchPersistedEvidence } from './retrieval';
const ROOT = path.resolve(__dirname, '../../..');
const xml = fs.readFileSync(path.join(ROOT, 'validation/acquisition/bsb/authentic-selected-records.v1.xml'), 'utf8');
const safe: WriteEnvironment = { runtime: 'test', allowWrites: true, namespace: 'phase8g_test', isolation: 'HERMETIC', productionApproval: false };
const run = (repository: MemoryEvidenceRepository, archive: MemoryRawArchive, body = xml, now = '2026-10-09T12:00:00.000Z', beforePublish?: () => void) => importBsbEvidence({ xml: body, repository, archive, environment: safe, now, beforePublish });

describe('Phase 8G persistent evidence store', () => {
  it('imports the authentic fixture and publishes three non-authoritative candidates', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); const report = await run(repository, archive); expect(report).toMatchObject({ recordsObserved: 2, versionsCreated: 2, versionsReused: 0, candidatesProjected: 3 }); const state = await repository.readState(); expect(state.activeSnapshotId).toBe(report.snapshotId); expect([...state.candidates.values()].every((item) => item.candidate.reviewStatus === 'UNREVIEWED' && item.candidate.authorityStatus === 'NON_AUTHORITATIVE_CANDIDATE')).toBe(true); expect(archive.objects.size).toBe(1); });
  it('re-imports idempotently without duplicate raw objects, versions, candidates, or snapshots', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); const first = await run(repository, archive); const second = await run(repository, archive, xml, '2026-10-09T12:05:00.000Z'); const state = await repository.readState(); expect(second).toMatchObject({ rawCreated: false, versionsCreated: 0, versionsReused: 2, snapshotId: first.snapshotId }); expect(state.versions.size).toBe(2); expect(state.candidates.size).toBe(3); expect(state.snapshots.size).toBe(1); expect(archive.objects.size).toBe(1); });
  it('serializes concurrent duplicate imports safely', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await Promise.all([run(repository, archive), run(repository, archive)]); const state = await repository.readState(); expect(state.versions.size).toBe(2); expect(state.candidates.size).toBe(3); expect(state.snapshots.size).toBe(1); });
  it('retains record history when authentic content changes and never infers deletion', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await run(repository, archive); const changed = xml.replace('ادب فارسی</subfield>', 'ادب فارسی نو</subfield>'); await run(repository, archive, changed, '2026-10-10T12:00:00.000Z'); const state = await repository.readState(); expect(state.versions.size).toBe(3); const versions = [...state.versions.values()].filter((item) => item.sourceRecordId === '991071006889707356'); expect(versions).toHaveLength(2); expect(versions.filter((item) => item.current)).toHaveLength(1); expect(state.versions.has([...state.snapshots.values()][0].sourceVersionIds[0])).toBe(true); });
  it('leaves no database state after Blob failure', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); archive.failPut = true; await expect(run(repository, archive)).rejects.toThrow(/Blob upload/); expect((await repository.readState()).runs.size).toBe(0); });
  it('leaves an auditable orphan Blob but publishes no state after database failure', async () => { const repository = new MemoryEvidenceRepository(undefined, true); const archive = new MemoryRawArchive(); await expect(run(repository, archive)).rejects.toThrow(/commit failure/); expect(archive.objects.size).toBe(1); expect((await repository.readState()).activeSnapshotId).toBeNull(); });
  it('rejects checksum mismatch on archive read', async () => { const archive = new MemoryRawArchive(); const bytes = new TextEncoder().encode(xml); await expect(archive.putImmutable('x', bytes, '0'.repeat(64))).rejects.toThrow(/checksum/); });
  it('rolls back failed publication atomically', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); const first = await run(repository, archive); await expect(run(repository, archive, xml.replace('ادب فارسی</subfield>', 'ادب فارسی نو</subfield>'), '2026-10-10T12:00:00.000Z', () => { throw new Error('Injected validation failure'); })).rejects.toThrow(/validation failure/); expect((await repository.readState()).activeSnapshotId).toBe(first.snapshotId); });
  it('restores a previous verified snapshot manually', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); const first = await run(repository, archive); const second = await run(repository, archive, xml.replace('ادب فارسی</subfield>', 'ادب فارسی نو</subfield>'), '2026-10-10T12:00:00.000Z'); expect(second.snapshotId).not.toBe(first.snapshotId); await restoreSnapshot(repository, first.snapshotId, safe, '2026-10-11T12:00:00.000Z'); expect((await repository.readState()).activeSnapshotId).toBe(first.snapshotId); });
  it('reloads persisted state and searches through existing index semantics without SRU calls', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await run(repository, archive); const exact = await searchActiveEvidence(repository, 'ادب فارسی', { provider: 'BSB_SRU_MARCXML', category: 'WORK_TITLE' }); const normalized = await searchActiveEvidence(repository, 'ادب فارسي', { provider: 'BSB_SRU_MARCXML' }); expect(exact.matches).toHaveLength(1); expect(normalized.matches.map((item) => item.candidateId)).toEqual(exact.matches.map((item) => item.candidateId)); expect(exact.citations[0].sourceRecordId).toBe('991071006889707356'); expect(await searchActiveEvidence(repository, 'ادب فارسی', { reviewedOnly: true })).toMatchObject({ status: 'INSUFFICIENT_EVIDENCE', matches: [] }); });
  it('applies existing fail-closed index semantics to candidates loaded from Neon', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await run(repository, archive); const state = await repository.readState(); const candidates = [...state.candidates.values()].map((item) => item.candidate); const reader = { activeCandidates: vi.fn(async () => candidates) }; expect(await searchPersistedEvidence(reader, 'ادب فارسی', { reviewedOnly: true })).toMatchObject({ status: 'INSUFFICIENT_EVIDENCE', matches: [] }); expect(reader.activeCandidates).toHaveBeenCalledWith('ادب فارسی', 'ادب فارسی', { category: undefined, provider: undefined, limit: 25 }); });
  it('rejects unbounded retrieval', async () => { await expect(searchActiveEvidence(new MemoryEvidenceRepository(), 'x', { limit: 101 })).rejects.toThrow(/1\.\.100/); });
  it('fails closed for shared/unknown Preview and unapproved Production', () => { expect(() => assertSafeEvidenceWrite({ ...safe, runtime: 'preview', isolation: 'SHARED_OR_UNKNOWN' })).toThrow(/isolation/); expect(() => assertSafeEvidenceWrite({ ...safe, runtime: 'production' })).toThrow(/owner approval/); expect(() => assertSafeEvidenceWrite({ ...safe, namespace: 'production_evidence' })).toThrow(/namespace/); });
  it('does not expose credential values in guard failures', () => { const secret = 'postgresql://secret-password@example.invalid/db'; const environment = environmentFromProcess({ DATABASE_URL: secret, VERCEL_ENV: 'preview', EVIDENCE_ALLOW_WRITES: 'true', EVIDENCE_STORAGE_NAMESPACE: 'preview_a' }); expect(() => assertSafeEvidenceWrite(environment)).toThrowError(expect.not.stringContaining(secret)); });
  it('makes no network or LLM call during fixture ingestion', async () => { const fetchSpy = vi.spyOn(globalThis, 'fetch'); await run(new MemoryEvidenceRepository(), new MemoryRawArchive()); expect(fetchSpy).not.toHaveBeenCalled(); fetchSpy.mockRestore(); });
});
