import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it, vi } from 'vitest';
import { assertDatabaseBinding, assertSafeEvidenceWrite, databaseIdentityFingerprint, environmentFromProcess, type WriteEnvironment } from './guard';
import { importBsbEvidence, restoreSnapshot } from './ingestion';
import { MemoryEvidenceRepository, MemoryRawArchive } from './memory';
import { importBsbEvidencePersistent } from './persistent';
import { searchActiveEvidence, searchPersistedEvidence } from './retrieval';
import { VercelPrivateBlobArchive } from './vercelBlob';
const ROOT = path.resolve(__dirname, '../../..');
const xml = fs.readFileSync(path.join(ROOT, 'validation/acquisition/bsb/authentic-selected-records.v1.xml'), 'utf8');
const marcRecords = [...xml.matchAll(/<record>[\s\S]*?<\/record>/gu)].map((match) => match[0]);
const collection = (...records: string[]) => `<?xml version="1.0" encoding="UTF-8"?><collection xmlns="http://www.loc.gov/MARC21/slim">${records.join('')}</collection>`;
const importA = collection(...marcRecords);
const importB = collection(
  marcRecords[0].replace('991071006889707356', 'phase8g-b-001').replace('ادب فارسی', 'تاریخ ایران'),
  marcRecords[1].replace('991144600686807356', 'phase8g-b-002').replace('ادب فارسى :', 'فرهنگ ایران :'),
);
const safe: WriteEnvironment = { runtime: 'test', allowWrites: true, namespace: 'phase8g_test', isolation: 'HERMETIC', productionApproval: false, administrator: true };
const run = (repository: MemoryEvidenceRepository, archive: MemoryRawArchive, body = xml, now = '2026-10-09T12:00:00.000Z', beforePublish?: () => void) => importBsbEvidence({ xml: body, repository, archive, environment: safe, now, beforePublish });

describe('Phase 8G persistent evidence store', () => {
  it('imports the authentic fixture and publishes three non-authoritative candidates', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); const report = await run(repository, archive); expect(report).toMatchObject({ recordsObserved: 2, versionsCreated: 2, versionsReused: 0, candidatesProjected: 3 }); const state = await repository.readState(); expect(state.activeSnapshotId).toBe(report.snapshotId); expect([...state.candidates.values()].every((item) => item.candidate.reviewStatus === 'UNREVIEWED' && item.candidate.authorityStatus === 'NON_AUTHORITATIVE_CANDIDATE')).toBe(true); expect(archive.objects.size).toBe(1); });
  it('re-imports idempotently without duplicate raw objects, versions, candidates, snapshots, or activation rewrites', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); const first = await run(repository, archive); const second = await run(repository, archive, xml, '2026-10-09T12:05:00.000Z'); const state = await repository.readState(); expect(second).toMatchObject({ rawCreated: false, versionsCreated: 0, versionsReused: 2, snapshotId: first.snapshotId }); expect(state.versions.size).toBe(2); expect(state.candidates.size).toBe(3); expect(state.snapshots.size).toBe(1); expect(state.snapshots.get(first.snapshotId)?.activatedAt).toBe('2026-10-09T12:00:00.000Z'); expect(archive.objects.size).toBe(1); });
  it('serializes concurrent duplicate imports safely', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await Promise.all([run(repository, archive), run(repository, archive)]); const state = await repository.readState(); expect(state.versions.size).toBe(2); expect(state.candidates.size).toBe(3); expect(state.snapshots.size).toBe(1); });
  it('retains record history when authentic content changes and never infers deletion', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await run(repository, archive); const changed = xml.replace('ادب فارسی</subfield>', 'ادب فارسی نو</subfield>'); await run(repository, archive, changed, '2026-10-10T12:00:00.000Z'); const state = await repository.readState(); expect(state.versions.size).toBe(3); const versions = [...state.versions.values()].filter((item) => item.sourceRecordId === '991071006889707356'); expect(versions).toHaveLength(2); expect(versions.filter((item) => item.current)).toHaveLength(1); expect(state.versions.has([...state.snapshots.values()][0].sourceVersionIds[0])).toBe(true); });
  it('leaves no database state after Blob failure', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); archive.failPut = true; await expect(run(repository, archive)).rejects.toThrow(/Blob upload/); expect((await repository.readState()).runs.size).toBe(0); });
  it('leaves an auditable orphan Blob but publishes no state after database failure', async () => { const repository = new MemoryEvidenceRepository(undefined, true); const archive = new MemoryRawArchive(); await expect(run(repository, archive)).rejects.toThrow(/commit failure/); expect(archive.objects.size).toBe(1); expect((await repository.readState()).activeSnapshotId).toBeNull(); });
  it('rejects checksum mismatch on archive read', async () => { const archive = new MemoryRawArchive(); const bytes = new TextEncoder().encode(xml); await expect(archive.putImmutable('x', bytes, '0'.repeat(64))).rejects.toThrow(/checksum/); });
  it('rolls back failed publication atomically', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); const first = await run(repository, archive); await expect(run(repository, archive, xml.replace('ادب فارسی</subfield>', 'ادب فارسی نو</subfield>'), '2026-10-10T12:00:00.000Z', () => { throw new Error('Injected validation failure'); })).rejects.toThrow(/validation failure/); expect((await repository.readState()).activeSnapshotId).toBe(first.snapshotId); });
  it('restores a previous verified snapshot manually', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); const first = await run(repository, archive); const second = await run(repository, archive, xml.replace('ادب فارسی</subfield>', 'ادب فارسی نو</subfield>'), '2026-10-10T12:00:00.000Z'); expect(second.snapshotId).not.toBe(first.snapshotId); await restoreSnapshot(repository, first.snapshotId, safe, '2026-10-11T12:00:00.000Z'); expect((await repository.readState()).activeSnapshotId).toBe(first.snapshotId); });
  it('reloads persisted state and searches through existing index semantics without SRU calls', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await run(repository, archive); const exact = await searchActiveEvidence(repository, 'ادب فارسی', { provider: 'BSB_SRU_MARCXML', category: 'WORK_TITLE' }); const normalized = await searchActiveEvidence(repository, 'ادب فارسي', { provider: 'BSB_SRU_MARCXML' }); expect(exact.matches).toHaveLength(1); expect(normalized.matches.map((item) => item.candidateId)).toEqual(exact.matches.map((item) => item.candidateId)); expect(exact.citations[0].sourceRecordId).toBe('991071006889707356'); expect(await searchActiveEvidence(repository, 'ادب فارسی', { reviewedOnly: true })).toMatchObject({ status: 'INSUFFICIENT_EVIDENCE', matches: [] }); });
  it('applies existing fail-closed index semantics to candidates loaded from Neon', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await run(repository, archive); const state = await repository.readState(); const candidates = [...state.candidates.values()].map((item) => item.candidate); const reader = { activeCandidates: vi.fn(async () => candidates) }; expect(await searchPersistedEvidence(reader, 'ادب فارسی', { reviewedOnly: true })).toMatchObject({ status: 'INSUFFICIENT_EVIDENCE', matches: [] }); expect(reader.activeCandidates).toHaveBeenCalledWith('ادب فارسی', 'ادب فارسی', { category: undefined, provider: undefined, limit: 25 }); });
  it('rejects unbounded retrieval', async () => { await expect(searchActiveEvidence(new MemoryEvidenceRepository(), 'x', { limit: 101 })).rejects.toThrow(/1\.\.100/); });
  it('fails closed for shared/unknown Preview and unapproved Production', () => { expect(() => assertSafeEvidenceWrite({ ...safe, runtime: 'preview', isolation: 'SHARED_OR_UNKNOWN' })).toThrow(/isolation/); expect(() => assertSafeEvidenceWrite({ ...safe, runtime: 'production' })).toThrow(/owner approval/); expect(() => assertSafeEvidenceWrite({ ...safe, namespace: 'production_evidence' })).toThrow(/namespace/); });
  it('requires actual database identity to match its database-resident binding', () => { const base = { host: 'isolated.example', database: 'evidence_test', user: 'evidence_admin', schema: 'public' }; const identity = { ...base, fingerprint: databaseIdentityFingerprint(base) }; const environment = { ...safe, isolation: 'ISOLATED_NEON_BRANCH' as const, expectedDatabaseFingerprint: identity.fingerprint, expectedBlobStoreId: 'store_test' }; const binding = { namespace: environment.namespace, runtime: environment.runtime, isolation: environment.isolation, databaseFingerprint: identity.fingerprint, writesEnabled: true }; expect(() => assertDatabaseBinding(environment, identity, binding)).not.toThrow(); expect(() => assertDatabaseBinding(environment, { ...identity, fingerprint: '0'.repeat(64) }, binding)).toThrow(/identity/); expect(() => assertDatabaseBinding(environment, identity, { ...binding, writesEnabled: false })).toThrow(/binding/); });
  it('enforces the Blob store identity at the adapter write boundary', async () => { const environment = { ...safe, isolation: 'ISOLATED_NEON_BRANCH' as const, expectedDatabaseFingerprint: '1'.repeat(64), expectedBlobStoreId: 'approved_store' }; const archive = new VercelPrivateBlobArchive(environment, 'lookalike_store'); await expect(archive.putImmutable(`evidence/${environment.namespace}/raw/sha256/${'0'.repeat(64)}.marcxml`, new Uint8Array([1]), '0'.repeat(64))).rejects.toThrow(/store identity/); });
  it('runs preflight before archive and publication in the real persistence workflow', async () => { const order: string[] = []; const archive = new MemoryRawArchive(); const originalPut = archive.putImmutable.bind(archive); archive.putImmutable = async (...args) => { order.push('archive'); return originalPut(...args); }; const publisher = { preflight: vi.fn(async () => { order.push('preflight'); return {} as never; }), publish: vi.fn(async (bundle) => { order.push('publish'); return { snapshotId: bundle.snapshot.snapshotId, previousSnapshotId: null, activeSnapshotId: bundle.snapshot.snapshotId, recordVersionCount: bundle.versions.length, candidateCount: bundle.projections.length }; }) }; const result = await importBsbEvidencePersistent({ xml, archive, publisher, environment: safe, now: '2026-10-09T12:00:00.000Z' }); expect(order).toEqual(['preflight', 'archive', 'publish']); expect(result).toMatchObject({ recordsObserved: 2, recordVersionCount: 2, candidateCount: 3 }); });
  it('incrementally preserves disjoint records, replaces changed records, deduplicates retries, and restores a complete prior corpus', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await run(repository, archive, importA); const combined = await run(repository, archive, importB, '2026-10-10T12:00:00.000Z'); let state = await repository.readState(); expect(state.snapshots.get(combined.snapshotId)?.sourceVersionIds).toHaveLength(4); expect(await searchActiveEvidence(repository, 'ادب فارسی')).toMatchObject({ status: 'CANDIDATE' }); expect(await searchActiveEvidence(repository, 'تاریخ ایران')).toMatchObject({ status: 'CANDIDATE' }); const changedA = collection(marcRecords[0].replace('ادب فارسی', 'ادب فارسی نو')); const changed = await run(repository, archive, changedA, '2026-10-11T12:00:00.000Z'); state = await repository.readState(); expect(state.snapshots.get(changed.snapshotId)?.sourceVersionIds).toHaveLength(4); expect([...state.versions.values()].filter((version) => version.sourceRecordId === '991071006889707356')).toHaveLength(2); expect((await searchActiveEvidence(repository, 'ادب فارسی نو')).matches).toHaveLength(1); expect((await searchActiveEvidence(repository, 'ادب فارسی')).matches).toHaveLength(0); const candidateCount = state.snapshots.get(changed.snapshotId)?.candidateCount; await run(repository, archive, importB, '2026-10-12T12:00:00.000Z'); state = await repository.readState(); expect(state.snapshots.get(state.activeSnapshotId!)?.candidateCount).toBe(candidateCount); await restoreSnapshot(repository, combined.snapshotId, safe, '2026-10-13T12:00:00.000Z'); expect((await searchActiveEvidence(repository, 'ادب فارسی')).matches).toHaveLength(1); expect((await searchActiveEvidence(repository, 'تاریخ ایران')).matches).toHaveLength(1); });
  it('serializes concurrent disjoint imports without losing active evidence', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await run(repository, archive, importA); const importC = collection(marcRecords[0].replace('991071006889707356', 'phase8g-c-001').replace('ادب فارسی', 'جامعه ایران')); const importD = collection(marcRecords[1].replace('991144600686807356', 'phase8g-d-001').replace('ادب فارسى :', 'زبان ایران :')); await Promise.all([run(repository, archive, importC, '2026-10-10T12:00:00.000Z'), run(repository, archive, importD, '2026-10-10T12:00:01.000Z')]); const state = await repository.readState(); expect(state.snapshots.get(state.activeSnapshotId!)?.sourceVersionIds).toHaveLength(4); expect((await searchActiveEvidence(repository, 'جامعه ایران')).matches).toHaveLength(1); const dCandidate = [...state.candidates.values()].find((item) => item.snapshotId === state.activeSnapshotId && item.candidate.sourceRecordIds.includes('phase8g-d-001'))?.candidate; expect(dCandidate).toBeDefined(); expect((await searchActiveEvidence(repository, dCandidate!.originalPersianForm)).matches).toHaveLength(1); });
  it('defines full rebuild as replacing active membership without deleting history', async () => { const repository = new MemoryEvidenceRepository(); const archive = new MemoryRawArchive(); await run(repository, archive, importA); await run(repository, archive, importB, '2026-10-10T12:00:00.000Z'); await importBsbEvidence({ xml: importB, repository, archive, environment: safe, now: '2026-10-11T12:00:00.000Z', mode: 'FULL_REBUILD' }); const state = await repository.readState(); expect(state.snapshots.get(state.activeSnapshotId!)?.sourceVersionIds).toHaveLength(2); expect(state.versions.size).toBe(4); expect((await searchActiveEvidence(repository, 'ادب فارسی')).matches).toHaveLength(0); expect((await searchActiveEvidence(repository, 'تاریخ ایران')).matches).toHaveLength(1); });
  it('produces the same combined manifest regardless of incremental import order', async () => { const forward = new MemoryEvidenceRepository(); const reverse = new MemoryEvidenceRepository(); await run(forward, new MemoryRawArchive(), importA, '2026-10-09T12:00:00.000Z'); await run(forward, new MemoryRawArchive(), importB, '2026-10-10T12:00:00.000Z'); await run(reverse, new MemoryRawArchive(), importB, '2026-10-09T12:00:00.000Z'); await run(reverse, new MemoryRawArchive(), importA, '2026-10-10T12:00:00.000Z'); const forwardState = await forward.readState(); const reverseState = await reverse.readState(); expect(forwardState.activeSnapshotId).toBe(reverseState.activeSnapshotId); expect(forwardState.snapshots.get(forwardState.activeSnapshotId!)?.manifestChecksum).toBe(reverseState.snapshots.get(reverseState.activeSnapshotId!)?.manifestChecksum); });
  it('does not expose credential values in guard failures', () => { const secret = 'postgresql://secret-password@example.invalid/db'; const environment = environmentFromProcess({ DATABASE_URL: secret, VERCEL_ENV: 'preview', EVIDENCE_ALLOW_WRITES: 'true', EVIDENCE_STORAGE_NAMESPACE: 'preview_a' }); expect(() => assertSafeEvidenceWrite(environment)).toThrowError(expect.not.stringContaining(secret)); });
  it('makes no network or LLM call during fixture ingestion', async () => { const fetchSpy = vi.spyOn(globalThis, 'fetch'); await run(new MemoryEvidenceRepository(), new MemoryRawArchive()); expect(fetchSpy).not.toHaveBeenCalled(); fetchSpy.mockRestore(); });
});
