import { createHash } from 'node:crypto';
import { adaptBsbRecord } from '../../validation/acquisition/bsb/adapter';
import { parseMarcCollection, parseSruMarcXml } from '../../validation/acquisition/bsb/marcxml';
import { lexicalCandidateSchema } from '../../validation/lexical-evidence/schema';
import { assertSafeEvidenceWrite, type WriteEnvironment } from './guard';
import type { EvidenceRepository, ImportReport, RawArchive, RetrievalSnapshot } from './types';
const sha = (value: string | Uint8Array) => createHash('sha256').update(value).digest('hex');
const stable = (value: unknown): string => JSON.stringify(value, (_key, item) => item instanceof Map ? [...item.entries()] : item, 0);
const recordsFromXml = (xml: string) => xml.includes('searchRetrieveResponse') ? parseSruMarcXml(xml).records : parseMarcCollection(xml);

export async function importBsbEvidence(options: { xml: string; repository: EvidenceRepository; archive: RawArchive; environment: WriteEnvironment; now: string; queryPlan?: unknown; requestBudget?: number; recordBudget?: number; beforePublish?: () => void }): Promise<ImportReport> {
  assertSafeEvidenceWrite(options.environment); const bytes = new TextEncoder().encode(options.xml); const rawChecksum = sha(bytes); const runId = `run-${rawChecksum.slice(0, 20)}`; const blobPath = `evidence/${options.environment.namespace}/raw/sha256/${rawChecksum}.marcxml`; const archived = await options.archive.putImmutable(blobPath, bytes, rawChecksum); await options.archive.readVerified(blobPath, rawChecksum); const records = recordsFromXml(options.xml);
  return options.repository.transaction(async (state) => { state.runs.set(runId, { runId, provider: 'BSB_SRU_MARCXML', queryPlan: options.queryPlan ?? { mode: 'AUTHENTIC_COMMITTED_FIXTURE' }, requestBudget: options.requestBudget ?? 0, recordBudget: options.recordBudget ?? records.length, status: 'RUNNING', startedAt: options.now, endedAt: null, error: null }); state.raw.set(rawChecksum, { checksum: rawChecksum, provider: 'BSB_SRU_MARCXML', blobPath, contentLength: bytes.byteLength, contentType: 'application/marcxml+xml', retrievedAt: options.now, licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/', runId });
    let versionsCreated = 0; let versionsReused = 0; const sourceVersionIds: string[] = []; const projected = [];
    for (const record of records) { const sourceRecordId = record.controlfields.find((field) => field.tag === '001')?.value; if (!sourceRecordId) throw new Error('Record lacks provider identity'); const recordChecksum = sha(record.rawXml); const versionId = `BSB_SRU_MARCXML:${sourceRecordId}:${recordChecksum}`; sourceVersionIds.push(versionId); const existing = state.versions.get(versionId); if (existing) { existing.lastSeenAt = options.now; versionsReused += 1; } else { for (const version of state.versions.values()) if (version.provider === 'BSB_SRU_MARCXML' && version.sourceRecordId === sourceRecordId) version.current = false; state.versions.set(versionId, { versionId, provider: 'BSB_SRU_MARCXML', sourceRecordId, recordChecksum, rawChecksum, marc: record, languageEvidence: record.datafields.filter((field) => field.tag === '041').flatMap((field) => field.subfields.filter((subfield) => subfield.code === 'a').map((subfield) => subfield.value)), firstSeenAt: options.now, lastSeenAt: options.now, current: true }); versionsCreated += 1; } for (const candidate of adaptBsbRecord(record)) projected.push({ sourceVersionId: versionId, candidate: lexicalCandidateSchema.parse(candidate) }); }
    sourceVersionIds.sort(); projected.sort((a, b) => a.candidate.candidateId.localeCompare(b.candidate.candidateId)); const manifest = { schemaVersion: 'phase8g-snapshot-v1', extractionVersion: 'phase8f-bsb-v1', sourceVersionIds, candidates: projected.map((item) => ({ candidateId: item.candidate.candidateId, contentHash: item.candidate.contentHash, sourceVersionId: item.sourceVersionId })) }; const manifestChecksum = sha(stable(manifest)); const snapshotId = `snapshot-${manifestChecksum.slice(0, 24)}`; const previousSnapshotId = state.activeSnapshotId; const snapshot: RetrievalSnapshot = { snapshotId, schemaVersion: 'phase8g-snapshot-v1', extractionVersion: 'phase8f-bsb-v1', sourceVersionIds, candidateCount: projected.length, manifestChecksum, status: 'DRAFT', createdAt: options.now, activatedAt: null }; state.snapshots.set(snapshotId, snapshot); for (const [key, value] of state.candidates) if (value.snapshotId === snapshotId) state.candidates.delete(key); for (const item of projected) state.candidates.set(`${snapshotId}:${item.candidate.candidateId}:${item.sourceVersionId}`, { snapshotId, ...item }); if (snapshot.candidateCount !== projected.length || snapshot.manifestChecksum !== sha(stable(manifest))) throw new Error('Snapshot validation failed'); snapshot.status = 'VERIFIED'; options.beforePublish?.(); if (previousSnapshotId && previousSnapshotId !== snapshotId) { const previous = state.snapshots.get(previousSnapshotId); if (previous) previous.status = 'RETIRED'; } snapshot.status = 'ACTIVE'; snapshot.activatedAt = options.now; state.activeSnapshotId = snapshotId; const run = state.runs.get(runId)!; run.status = 'COMPLETE'; run.endedAt = options.now; return { runId, rawChecksum, rawCreated: archived.created, recordsObserved: records.length, versionsCreated, versionsReused, candidatesProjected: projected.length, snapshotId, previousSnapshotId, activeSnapshotId: snapshotId }; });
}

export async function restoreSnapshot(repository: EvidenceRepository, snapshotId: string, environment: WriteEnvironment, now: string): Promise<void> { assertSafeEvidenceWrite(environment); await repository.transaction(async (state) => { const target = state.snapshots.get(snapshotId); if (!target || !['ACTIVE', 'RETIRED', 'VERIFIED'].includes(target.status)) throw new Error('Snapshot is not verified and restorable'); const active = state.activeSnapshotId ? state.snapshots.get(state.activeSnapshotId) : undefined; if (active) active.status = 'RETIRED'; target.status = 'ACTIVE'; target.activatedAt = now; state.activeSnapshotId = snapshotId; }); }
