import { neon } from '@neondatabase/serverless';
import { lexicalCandidateSchema } from '../../validation/lexical-evidence/schema';
import type { EvidenceProvider, LexicalCandidate, LexicalCandidateCategory } from '../../validation/lexical-evidence/types';
import type { AcquisitionRun, CandidateProjection, RawSourceObject, RecordVersion, RetrievalSnapshot } from './types';
export class NeonEvidenceReader { private readonly sql; constructor(connectionString: string) { if (!connectionString) throw new Error('DATABASE_URL is required'); this.sql = neon(connectionString); } async activeCandidates(query: string, normalized: string, options: { category?: LexicalCandidateCategory; provider?: EvidenceProvider; limit: number }): Promise<LexicalCandidate[]> { const rows = await this.sql.query('SELECT cp.candidate_json FROM evidence_active_snapshot a JOIN evidence_candidate_projection cp ON cp.snapshot_id = a.snapshot_id WHERE a.singleton = true AND (cp.persian_form = $1 OR cp.normalized_form = $2) AND ($3::text IS NULL OR cp.category = $3) AND ($4::text IS NULL OR cp.provider = $4) ORDER BY cp.candidate_id LIMIT $5', [query, normalized, options.category ?? null, options.provider ?? null, options.limit]); return rows.map((row) => lexicalCandidateSchema.parse(row.candidate_json)); } }

export interface NeonPublicationBundle { run: AcquisitionRun; raw: RawSourceObject; versions: RecordVersion[]; projections: CandidateProjection[]; snapshot: RetrievalSnapshot; }
export class NeonSnapshotPublisher { private readonly sql; constructor(connectionString: string) { if (!connectionString) throw new Error('DATABASE_URL is required'); this.sql = neon(connectionString); } async publish(bundle: NeonPublicationBundle): Promise<void> { if (bundle.snapshot.status !== 'VERIFIED' || bundle.snapshot.candidateCount !== bundle.projections.length) throw new Error('Only a complete verified snapshot can be published'); if (bundle.projections.some((item) => item.candidate.reviewStatus !== 'UNREVIEWED' || item.candidate.authorityStatus !== 'NON_AUTHORITATIVE_CANDIDATE')) throw new Error('BSB publication cannot contain authoritative candidates'); const queries = [
      this.sql`INSERT INTO evidence_acquisition_run(run_id,provider,query_plan,request_budget,record_budget,status,started_at,ended_at,error_details) VALUES (${bundle.run.runId},${bundle.run.provider},${JSON.stringify(bundle.run.queryPlan)}::jsonb,${bundle.run.requestBudget},${bundle.run.recordBudget},'RUNNING',${bundle.run.startedAt},NULL,NULL) ON CONFLICT (run_id) DO NOTHING`,
      this.sql`INSERT INTO evidence_raw_source(checksum,provider,blob_path,content_length,content_type,retrieved_at,license_url,run_id) VALUES (${bundle.raw.checksum},${bundle.raw.provider},${bundle.raw.blobPath},${bundle.raw.contentLength},${bundle.raw.contentType},${bundle.raw.retrievedAt},${bundle.raw.licenseUrl},${bundle.raw.runId}) ON CONFLICT (checksum) DO NOTHING`,
      ...bundle.versions.flatMap((version) => [this.sql`UPDATE evidence_record_version SET is_current=false,last_seen_at=${version.lastSeenAt} WHERE provider=${version.provider} AND source_record_id=${version.sourceRecordId} AND version_id<>${version.versionId}`, this.sql`INSERT INTO evidence_record_version(version_id,provider,source_record_id,record_checksum,raw_checksum,marc_json,language_evidence,first_seen_at,last_seen_at,is_current) VALUES (${version.versionId},${version.provider},${version.sourceRecordId},${version.recordChecksum},${version.rawChecksum},${JSON.stringify(version.marc)}::jsonb,${JSON.stringify(version.languageEvidence)}::jsonb,${version.firstSeenAt},${version.lastSeenAt},true) ON CONFLICT (version_id) DO UPDATE SET last_seen_at=excluded.last_seen_at,is_current=true`]),
      this.sql`INSERT INTO evidence_snapshot(snapshot_id,schema_version,extraction_version,source_version_ids,candidate_count,manifest_checksum,status,created_at,activated_at) VALUES (${bundle.snapshot.snapshotId},${bundle.snapshot.schemaVersion},${bundle.snapshot.extractionVersion},${JSON.stringify(bundle.snapshot.sourceVersionIds)}::jsonb,${bundle.snapshot.candidateCount},${bundle.snapshot.manifestChecksum},'DRAFT',${bundle.snapshot.createdAt},NULL) ON CONFLICT (snapshot_id) DO NOTHING`,
      ...bundle.projections.map((projection) => this.sql`INSERT INTO evidence_candidate_projection(snapshot_id,candidate_id,source_version_id,provider,persian_form,normalized_form,category,candidate_json,content_hash,review_status,authority_status) VALUES (${bundle.snapshot.snapshotId},${projection.candidate.candidateId},${projection.sourceVersionId},'BSB_SRU_MARCXML',${projection.candidate.originalPersianForm},${projection.candidate.normalizedSearchForm},${projection.candidate.category},${JSON.stringify(projection.candidate)}::jsonb,${projection.candidate.contentHash},'UNREVIEWED','NON_AUTHORITATIVE_CANDIDATE') ON CONFLICT DO NOTHING`),
      this.sql`UPDATE evidence_snapshot SET status='VERIFIED' WHERE snapshot_id=${bundle.snapshot.snapshotId} AND candidate_count=(SELECT count(*) FROM evidence_candidate_projection WHERE snapshot_id=${bundle.snapshot.snapshotId})`,
      this.sql`SELECT CASE WHEN EXISTS(SELECT 1 FROM evidence_snapshot WHERE snapshot_id=${bundle.snapshot.snapshotId} AND status='VERIFIED') THEN 1 ELSE 1/0 END AS publication_guard`,
      this.sql`UPDATE evidence_snapshot SET status='RETIRED' WHERE status='ACTIVE' AND snapshot_id<>${bundle.snapshot.snapshotId}`,
      this.sql`INSERT INTO evidence_active_snapshot(singleton,snapshot_id) SELECT true,${bundle.snapshot.snapshotId} FROM evidence_snapshot WHERE snapshot_id=${bundle.snapshot.snapshotId} AND status='VERIFIED' ON CONFLICT(singleton) DO UPDATE SET snapshot_id=excluded.snapshot_id`,
      this.sql`UPDATE evidence_snapshot SET status='ACTIVE',activated_at=${bundle.snapshot.activatedAt ?? bundle.run.endedAt} WHERE snapshot_id=${bundle.snapshot.snapshotId} AND EXISTS(SELECT 1 FROM evidence_active_snapshot WHERE snapshot_id=${bundle.snapshot.snapshotId})`,
      this.sql`UPDATE evidence_acquisition_run SET status='COMPLETE',ended_at=${bundle.run.endedAt} WHERE run_id=${bundle.run.runId}`
    ]; await this.sql.transaction(queries, { isolationLevel: 'Serializable' }); } }
