import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it, vi } from 'vitest';
import { LexicalEvidenceIndex } from '../../lexical-evidence/index';
import { extractLexicalCandidates } from '../../lexical-evidence/extractor';
import { adaptBsbRecord } from './adapter';
import { buildSruUrl, fetchSruPage } from './client';
import { parseMarcCollection, parseMarcRecord, parseSruMarcXml, XML_LIMITS } from './marcxml';

const fixture = fs.readFileSync(path.resolve(__dirname, '../../../../validation/acquisition/bsb/authentic-selected-records.v1.xml'), 'utf8');
const records = parseMarcCollection(fixture);
const envelope = (body: string, total = 1, next = '') => `<searchRetrieveResponse xmlns="http://www.loc.gov/zing/srw/"><version>1.2</version><numberOfRecords>${total}</numberOfRecords><records>${body}</records>${next}</searchRetrieveResponse>`;
const wrappedRecord = (record: string, position = 1) => `<record><recordSchema>marcxml</recordSchema><recordPacking>xml</recordPacking><recordData>${record}</recordData><recordPosition>${position}</recordPosition></record>`;

describe('Phase 8F BSB acquisition', () => {
  it('builds allowlisted CQL and bounded 1-based pagination', () => { const url = buildSruUrl({ index: 'language', relation: '==', term: 'per' }, 1, 50); expect(url.searchParams.get('query')).toBe('language=="per"'); expect(url.searchParams.get('recordSchema')).toBe('marcxml'); expect(() => buildSruUrl({ index: 'evil', relation: '=', term: 'x' }, 1, 1)).toThrow(); expect(() => buildSruUrl({ index: 'language', relation: '=', term: 'per' }, 0, 51)).toThrow(); });
  it('parses authentic default-namespace MARC while preserving order, namespaces, indicators, subfields, and entities', () => { expect(records).toHaveLength(2); expect(records[0].namespaceUri).toBe('http://www.loc.gov/MARC21/slim'); expect(records[0].datafields.map((field) => field.tag)).toEqual(['041', '245', '880', '246']); expect(records[0].datafields.find((field) => field.tag === '245')).toMatchObject({ ind1: '1', ind2: '0' }); expect(records[0].datafields.find((field) => field.tag === '245')?.subfields.map((field) => field.code)).toEqual(['6', 'a', 'b']); });
  it('parses namespace-prefixed MARC records', () => { const prefixed = records[0].rawXml.replace('<record xmlns=', '<marc:record xmlns:marc=').replace('</record>', '</marc:record>').replaceAll('<leader>', '<marc:leader>').replaceAll('</leader>', '</marc:leader>').replaceAll('<controlfield', '<marc:controlfield').replaceAll('</controlfield>', '</marc:controlfield>').replaceAll('<datafield', '<marc:datafield').replaceAll('</datafield>', '</marc:datafield>').replaceAll('<subfield', '<marc:subfield').replaceAll('</subfield>', '</marc:subfield>'); expect(parseMarcRecord(prefixed).datafields.length).toBe(4); });
  it.each(['<!DOCTYPE record SYSTEM "x">', '<!ENTITY xxe SYSTEM "file:///etc/passwd">', '<?xml-stylesheet href="x"?>'])('rejects active XML declarations: %s', (declaration) => expect(() => parseMarcRecord(`${declaration}<record/>`)).toThrow());
  it('validates SRU response counts, positions, and pagination', () => { const xml = envelope(`${wrappedRecord(records[0].rawXml, 7)}${wrappedRecord(records[1].rawXml, 8)}`, 20, '<nextRecordPosition>9</nextRecordPosition>'); expect(parseSruMarcXml(xml)).toMatchObject({ numberOfRecords: 20, recordPositions: [7, 8], nextRecordPosition: 9 }); expect(() => parseSruMarcXml(envelope(wrappedRecord(records[0].rawXml, 2), 0))).toThrow(/more records/); expect(() => parseSruMarcXml(envelope(`${wrappedRecord(records[0].rawXml, 1)}${wrappedRecord(records[1].rawXml, 3)}`, 3))).toThrow(/not contiguous/); expect(() => parseSruMarcXml(envelope(wrappedRecord(records[0].rawXml, 1), 1, '<nextRecordPosition>7</nextRecordPosition>'))).toThrow(/nextRecordPosition/); });
  it('reports SRU diagnostics explicitly', async () => { const diagnostic = `<searchRetrieveResponse xmlns="http://www.loc.gov/zing/srw/" xmlns:diag="http://www.loc.gov/zing/srw/diagnostic/"><version>1.2</version><numberOfRecords>0</numberOfRecords><diag:diagnostics><diag:diagnostic><diag:uri>info:srw/diagnostic/1/7</diag:uri><diag:message>Unsupported query</diag:message><diag:details>bad index</diag:details></diag:diagnostic></diag:diagnostics></searchRetrieveResponse>`; expect(parseSruMarcXml(diagnostic).diagnostics[0]).toMatchObject({ message: 'Unsupported query', details: 'bad index' }); const url = buildSruUrl({ index: 'language', relation: '==', term: 'per' }, 1, 1); await expect(fetchSruPage(url, vi.fn(async () => new Response(diagnostic)))).rejects.toMatchObject({ diagnostics: [{ message: 'Unsupported query' }], log: { outcome: 'SRU_DIAGNOSTIC' } }); });
  it('rejects malformed, oversized, over-deep, and structurally unexpected XML', () => { expect(() => parseMarcRecord('<record xmlns="http://www.loc.gov/MARC21/slim"><x></record>')).toThrow(); const deep = `<searchRetrieveResponse xmlns="http://www.loc.gov/zing/srw/"><version>1.2</version><numberOfRecords>0</numberOfRecords>${'<extraResponseData>'.repeat(XML_LIMITS.maxDepth)}${'</extraResponseData>'.repeat(XML_LIMITS.maxDepth)}</searchRetrieveResponse>`; expect(() => parseSruMarcXml(deep)).toThrow(/depth/); expect(() => parseMarcRecord('x'.repeat(XML_LIMITS.maxBytes + 1))).toThrow(/byte limit/); expect(() => parseMarcRecord('<record xmlns="urn:wrong"><controlfield tag="001">1</controlfield></record>')).toThrow(/Unexpected XML root/); expect(() => parseMarcRecord('<record xmlns="http://www.loc.gov/MARC21/slim"><datafield tag="245" ind1="1"><subfield code="a">x</subfield></datafield></record>')).toThrow(/attributes/); });
  it('surfaces logged HTTP/network errors', async () => { const url = buildSruUrl({ index: 'language', relation: '==', term: 'per' }, 1, 1); await expect(fetchSruPage(url, vi.fn(async () => { throw new Error('network down'); }))).rejects.toMatchObject({ log: { outcome: 'TIMEOUT_OR_NETWORK_ERROR' } }); await expect(fetchSruPage(url, vi.fn(async () => new Response('', { status: 503 })))).rejects.toMatchObject({ log: { outcome: 'HTTP_ERROR', status: 503 } }); });
  it('rejects oversized response bodies before parsing', async () => { const url = buildSruUrl({ index: 'language', relation: '==', term: 'per' }, 1, 1); const response = new Response('small', { headers: { 'content-length': String(XML_LIMITS.maxBytes + 1) } }); await expect(fetchSruPage(url, vi.fn(async () => response))).rejects.toThrow(/byte limit/); });
  it('links 880 titles and names, treats 246 indicator 1 as parallel/undetermined, and grants no authority', () => { const candidates = records.flatMap(adaptBsbRecord); expect(candidates.some((item) => item.category === 'WORK_TITLE' && item.originalPersianForm.includes('ادب فارسی'))).toBe(true); expect(candidates.some((item) => item.category === 'ORGANIZATION_NAME')).toBe(true); expect(candidates.every((item) => item.authorityStatus === 'NON_AUTHORITATIVE_CANDIDATE' && item.reviewStatus === 'UNREVIEWED')).toBe(true); const title = candidates.find((item) => item.originalPersianForm.includes('ادب فارسی'))!; expect(title.observedLatinVariants.map((item) => item.classification)).toEqual(['ROMANIZATION_CANDIDATE', 'UNDETERMINED_LATIN_VARIANT']); expect(title.providerEvidence?.find((item) => item.sourceField === '246')).toMatchObject({ relationship: 'PARALLEL_TITLE', indicators: ['1', '1'] }); });
  it('keeps unmatched and contradictory 880 linkage visible as uncertain evidence', () => { const unmatched = structuredClone(records[0]); unmatched.datafields = unmatched.datafields.filter((field) => field.tag !== '245'); expect(adaptBsbRecord(unmatched)[0].providerEvidence?.[0]).toMatchObject({ relationship: 'UNCERTAIN_VARIANT' }); const duplicate = structuredClone(records[0]); duplicate.datafields.push(structuredClone(duplicate.datafields.find((field) => field.tag === '245')!)); expect(adaptBsbRecord(duplicate)[0].providerEvidence?.[0]).toMatchObject({ relationship: 'UNCERTAIN_VARIANT' }); });
  it('uses an authentic 856 link when present and otherwise identifies the SRU endpoint without inventing a permalink', () => { const withLink = structuredClone(records[0]); withLink.datafields.push({ namespaceUri: withLink.namespaceUri, tag: '856', ind1: '4', ind2: '0', subfields: [{ namespaceUri: withLink.namespaceUri, code: 'u', value: 'https://www.digitale-sammlungen.de/en/view/bsb123' }] }); expect(adaptBsbRecord(withLink)[0].sourceUrls).toEqual(['https://www.digitale-sammlungen.de/en/view/bsb123']); const without = adaptBsbRecord(records[0])[0]; expect(without.sourceUrls).toEqual(['https://bsb.alma.exlibrisgroup.com/view/sru/49BVB_BSB']); expect(without.sourceUrls[0]).not.toContain('identifier'); });
  it('separates cross-provider identities and supports source filtering, normalization, category and reviewed-only gates', () => { const bsb = records.flatMap(adaptBsbRecord); const index = new LexicalEvidenceIndex(bsb); const exact = index.search('ادب فارسی', { provider: 'BSB_SRU_MARCXML', category: 'WORK_TITLE' }); expect(exact.matches).toHaveLength(1); expect(index.search('ادب فارسي', { provider: 'BSB_SRU_MARCXML' }).matches).toHaveLength(1); expect(index.search('ادب فارسی', { provider: 'CINII_RESEARCH_OPENSEARCH_V2' }).matches).toHaveLength(0); expect(index.search('ادب فارسی', { reviewedOnly: true }).status).toBe('INSUFFICIENT_EVIDENCE'); expect(exact.citations[0].sourceRecordId).toBe('991071006889707356'); const clone = structuredClone(bsb[0]); clone.providerEvidence = clone.providerEvidence?.map((item) => ({ ...item, provider: 'CINII_RESEARCH_OPENSEARCH_V2' })); expect(clone.candidateId).toBe(bsb[0].candidateId); });
  it('keeps CiNii v1 candidates readable and deterministic', () => { const source = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../../../validation/acquisition/cinii/offline-pilot.v1.json'), 'utf8')); const first = extractLexicalCandidates(source.records); expect(first).toEqual(extractLexicalCandidates(source.records)); expect(first.every((item) => item.providerEvidence === undefined)).toBe(true); });
  it('rejects Arabic-script records without Persian language metadata', () => { const record = structuredClone(records[0]); record.datafields = record.datafields.filter((field) => field.tag !== '041'); record.controlfields = record.controlfields.filter((field) => field.tag !== '008'); expect(adaptBsbRecord(record)).toEqual([]); });
});
