import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it, vi } from 'vitest';
import { LexicalEvidenceIndex } from '../../lexical-evidence/index';
import { extractLexicalCandidates } from '../../lexical-evidence/extractor';
import { adaptBsbRecord } from './adapter';
import { buildSruUrl, fetchSruPage } from './client';
import { parseMarcRecord, parseSruMarcXml } from './marcxml';

const fixture = fs.readFileSync(path.resolve(__dirname, '../../../../validation/acquisition/bsb/authentic-selected-records.v1.xml'), 'utf8');
const records = [...fixture.matchAll(/<record>([\s\S]*?)<\/record>/gu)].map((match) => parseMarcRecord(`<record>${match[1]}</record>`));

describe('Phase 8F BSB acquisition', () => {
  it('builds allowlisted CQL and bounded 1-based pagination', () => { const url = buildSruUrl({ index: 'language', relation: '==', term: 'per' }, 1, 50); expect(url.searchParams.get('query')).toBe('language=="per"'); expect(url.searchParams.get('recordSchema')).toBe('marcxml'); expect(() => buildSruUrl({ index: 'evil', relation: '=', term: 'x' }, 1, 1)).toThrow(); expect(() => buildSruUrl({ index: 'language', relation: '=', term: 'per' }, 0, 51)).toThrow(); });
  it('parses default and prefixed MARC namespaces, repeated fields, indicators, and entities', () => { expect(records).toHaveLength(2); expect(records[0].datafields.filter((field) => field.tag === '245')).toHaveLength(1); expect(records[0].datafields.find((field) => field.tag === '245')?.ind1).toBe('1'); const prefixed = fixture.replaceAll('<collection', '<marc:collection').replaceAll('</collection>', '</marc:collection>').replaceAll('<record>', '<marc:record>').replaceAll('</record>', '</marc:record>').replaceAll('<leader>', '<marc:leader>').replaceAll('</leader>', '</marc:leader>').replaceAll('<controlfield', '<marc:controlfield').replaceAll('</controlfield>', '</marc:controlfield>').replaceAll('<datafield', '<marc:datafield').replaceAll('</datafield>', '</marc:datafield>').replaceAll('<subfield', '<marc:subfield').replaceAll('</subfield>', '</marc:subfield>'); expect(parseMarcRecord(prefixed).datafields.length).toBeGreaterThan(0); });
  it.each(['<!DOCTYPE record SYSTEM "x">', '<!ENTITY xxe SYSTEM "file:///etc/passwd">', '<?xml-stylesheet href="x"?>'])('rejects active XML declarations: %s', (declaration) => expect(() => parseMarcRecord(`${declaration}<record/>`)).toThrow(/Unsafe XML/));
  it('parses an SRU envelope and surfaces logged HTTP/network errors', async () => { const xml = `<searchRetrieveResponse><version>1.2</version><numberOfRecords>2</numberOfRecords><records><record><recordData>${fixture}</recordData></record></records><nextRecordPosition>3</nextRecordPosition></searchRetrieveResponse>`; expect(parseSruMarcXml(xml).numberOfRecords).toBe(2); const url = buildSruUrl({ index: 'language', relation: '==', term: 'per' }, 1, 1); const network = fetchSruPage(url, vi.fn(async () => { throw new Error('network down'); })); await expect(network).rejects.toMatchObject({ log: { outcome: 'TIMEOUT_OR_NETWORK_ERROR', recordsReceived: 0 } }); const http = fetchSruPage(url, vi.fn(async () => new Response('', { status: 503 }))); await expect(http).rejects.toMatchObject({ log: { outcome: 'HTTP_ERROR', status: 503 } }); });
  it('links 880 titles and names, distinguishes 246 translations, and grants no authority', () => { const candidates = records.flatMap(adaptBsbRecord); expect(candidates.some((item) => item.category === 'WORK_TITLE' && item.originalPersianForm.includes('ادب فارسی'))).toBe(true); expect(candidates.some((item) => item.category === 'ORGANIZATION_NAME')).toBe(true); expect(candidates.every((item) => item.authorityStatus === 'NON_AUTHORITATIVE_CANDIDATE' && item.reviewStatus === 'UNREVIEWED')).toBe(true); const classes = candidates.flatMap((item) => item.observedLatinVariants).map((item) => item.classification); expect(classes).toContain('ROMANIZATION_CANDIDATE'); expect(classes).toContain('TRANSLATED_TITLE'); });
  it('separates cross-provider identities and supports source filtering, normalization, category and reviewed-only gates', () => { const bsb = records.flatMap(adaptBsbRecord); const index = new LexicalEvidenceIndex(bsb); const exact = index.search('ادب فارسی', { provider: 'BSB_SRU_MARCXML', category: 'WORK_TITLE' }); expect(exact.matches).toHaveLength(1); expect(index.search('ادب فارسي', { provider: 'BSB_SRU_MARCXML' }).matches).toHaveLength(1); expect(index.search('ادب فارسی', { provider: 'CINII_RESEARCH_OPENSEARCH_V2' }).matches).toHaveLength(0); expect(index.search('ادب فارسی', { reviewedOnly: true }).status).toBe('INSUFFICIENT_EVIDENCE'); expect(exact.citations[0].sourceRecordId).toBe('991071006889707356'); const clone = structuredClone(bsb[0]); clone.providerEvidence = clone.providerEvidence?.map((item) => ({ ...item, provider: 'CINII_RESEARCH_OPENSEARCH_V2' })); expect(clone.candidateId).toBe(bsb[0].candidateId); });
  it('keeps CiNii v1 candidates readable and deterministic', () => { const source = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../../../validation/acquisition/cinii/offline-pilot.v1.json'), 'utf8')); const first = extractLexicalCandidates(source.records); expect(first).toEqual(extractLexicalCandidates(source.records)); expect(first.every((item) => item.providerEvidence === undefined)).toBe(true); });
  it('rejects Arabic-script records without Persian language metadata', () => { const record = structuredClone(records[0]); record.datafields = record.datafields.filter((field) => field.tag !== '041'); record.controlfields = record.controlfields.filter((field) => field.tag !== '008'); expect(adaptBsbRecord(record)).toEqual([]); });
});
