import { parseSruMarcXml, XML_LIMITS } from './marcxml';
import type { BsbRequestLog, SruDiagnostic, SruPage } from './types';
export const BSB_SRU_ENDPOINT = 'https://bsb.alma.exlibrisgroup.com/view/sru/49BVB_BSB';
export class SruRequestError extends Error { constructor(message: string, readonly log: BsbRequestLog) { super(message); this.name = 'SruRequestError'; } }
export class SruDiagnosticError extends SruRequestError { constructor(readonly diagnostics: SruDiagnostic[], log: BsbRequestLog) { super(`BSB SRU diagnostic: ${diagnostics.map((item) => `${item.uri} ${item.message}`).join('; ')}`, log); this.name = 'SruDiagnosticError'; } }
async function readBoundedXml(response: Response): Promise<string> { const declared = Number(response.headers.get('content-length')); if (Number.isFinite(declared) && declared > XML_LIMITS.maxBytes) throw new Error('BSB SRU response exceeds XML byte limit'); if (!response.body) return ''; const reader = response.body.getReader(); const chunks: Uint8Array[] = []; let bytes = 0; while (true) { const { done, value } = await reader.read(); if (done) break; bytes += value.byteLength; if (bytes > XML_LIMITS.maxBytes) { await reader.cancel(); throw new Error('BSB SRU response exceeds XML byte limit'); } chunks.push(value); } const combined = new Uint8Array(bytes); let offset = 0; for (const chunk of chunks) { combined.set(chunk, offset); offset += chunk.byteLength; } return new TextDecoder('utf-8', { fatal: true }).decode(combined); }
const ALLOWED_INDEXES = new Set(['language', 'all_for_ui', 'dc_title']);
export function buildSruUrl(query: { index: string; relation: '==' | 'all' | '='; term: string }, startRecord: number, maximumRecords: number): URL { if (!ALLOWED_INDEXES.has(query.index) || !query.term.trim()) throw new Error('Unsupported or empty CQL query'); if (!Number.isInteger(startRecord) || startRecord < 1 || !Number.isInteger(maximumRecords) || maximumRecords < 1 || maximumRecords > 50) throw new Error('Invalid SRU pagination'); const url = new URL(BSB_SRU_ENDPOINT); url.search = new URLSearchParams({ version: '1.2', operation: 'searchRetrieve', query: `${query.index}${query.relation === 'all' ? ' all ' : query.relation}"${query.term.replace(/["\\]/gu, '')}"`, startRecord: String(startRecord), maximumRecords: String(maximumRecords), recordSchema: 'marcxml' }).toString(); return url; }
export async function fetchSruPage(url: URL, fetchImpl: typeof fetch = fetch, timeoutMs = 20_000): Promise<{ page: SruPage; log: BsbRequestLog; xml: string }> { const startedAt = new Date().toISOString(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetchImpl(url, { signal: controller.signal, headers: { Accept: 'application/xml' } }); const endedAt = new Date().toISOString(); if (!response.ok) throw new SruRequestError(`BSB SRU HTTP ${response.status}`, { url: url.toString(), startedAt, endedAt, status: response.status, outcome: 'HTTP_ERROR', recordsReceived: 0 }); const xml = await readBoundedXml(response); const page = parseSruMarcXml(xml); if (page.diagnostics.length) throw new SruDiagnosticError(page.diagnostics, { url: url.toString(), startedAt, endedAt, status: response.status, outcome: 'SRU_DIAGNOSTIC', recordsReceived: 0 }); return { page, xml, log: { url: url.toString(), startedAt, endedAt, status: response.status, outcome: 'SUCCESS', recordsReceived: page.records.length } }; } catch (error) { if (error instanceof SruRequestError) throw error; throw new SruRequestError(error instanceof Error ? error.message : 'BSB SRU request failed', { url: url.toString(), startedAt, endedAt: new Date().toISOString(), status: null, outcome: 'TIMEOUT_OR_NETWORK_ERROR', recordsReceived: 0 }); } finally { clearTimeout(timer); } }
